[tool.black]
line-length = 119
target-version = ["py311"]

[tool.ruff]
line-length = 119
target-version = "py311"

[tool.pyright]
venvPath = ".direnv"

[tool.pip-tools]
emit-index-url = false
resolver = "backtracking"
generate-hashes = true